project:
  type: book
  output-dir: docs

book:
  title: "W3TM"
  author: "Rick Gilmore"
  date: "2023-05-26"
  cover-image: img/transylvania-epic-2023.jpeg
  chapters:
    - index.qmd
    - rigs.qmd
    - antennas.qmd
    - stations.qmd
    - computers.qmd
    - engagement.qmd

format:
  html:
    theme: cosmo
    