project:
  type: book
  output-dir: docs

book:
  title: "W3TM"
  author: "Rick Gilmore"
  date: "2023-05-26"
  cover-image: img/transylvania-epic-2023.jpeg
  chapters:
    - index.qmd
    - rigs.qmd
    - amplifiers.qmd
    - antennas.qmd
    - computers.qmd
    - power.qmd
    - stations.qmd
    - engagement.qmd
    - workbench.qmd
    - ft-891.qmd
    - ic-9700.qmd

format:
  html:
    theme: cosmo
    number-sections: false
    fig-align: center
    
    