---
title: "Stations"
format: html
editor: source
---

This page describes various stations that I use.

## Home

### Shack

#### APRS I-Gate

The W3TM-11 APRS I-Gate uses the [Kenwood TM-281A](rigs.qmd#kenwood-tm-281a) connected to a Mac Mini running Ubuntu and the direwolf software TNC. I have a 2 m/70 cm J-pole antenna on the roof of my house at about 6 m from the ground.

#### HF 1

My primary HF station that I am callign HF 1 just for fun uses the [FlexRadio 6400](rigs.qmd#flexradio-6400) transceiver.
The Flex drives an [SPE Expert Linear 1K amplifier](amplifiers.qmd#spe-expert-linear-1k).
The radio has an X microphone.
An Acer laptop running SmartSDR 3.x.x is used to control the radio.

#### HF 2

My second HF station runs an [IC-7300](rigs.qmd#icom-ic-7300).
It also connects to the [SPE Expert Linear 1K amplifier](amplifiers.qmd#spe-expert-linear-1k).
I use either the stock hand mic or a Heil (model) headset with a footswitch.

#### Allstar node

I have a [ClearNode](https://www.node-ventures.com/buy-clearnode/) UHF Allstar node on 51401.
The node also supports EchoLink (W3TM-L).

I used this node for the K3P Special Event station in June 2023. At least two hams connected via the node to participate in the event.

### Office

#### HF 3 (QRP/VHF/UHF)

A third HF station is located in my office.
I'm running the [IC-705](rigs.qmd#icom-ic-705).
At the moment, the HF capability is receive-only, as I have a [W6LVP](https://www.w6lvp.com/product/w6lvp-amplified-receive-only-magnetic-loop-antenna/) receive only magnetic loop for the HF antenna.
The VHF/UHF side of the rig is connected to a slim jim antenna.
Both antennas connect via a diplexer.

## Mobile

### Kia Forte

A [Kenwood TM-710GA](rigs.qmd#kenwood-tm-710ga) is used in this vehicle for FM (VHF & UHF) voice communications.
The rig also beacons APRS packets as W3TM-1.
I usually have it configured with APRS voice alert.

### Honda CRV

A [Yaesu FTM-400XDR](rigs.qmd#yaesu-FTM-400xdr) is used in this vehicle for FM (VHF & UHF) voice communications.
The rig also beacons APRS packets as W3TM-2.
I usually have it configured with APRS voice alert.

## Portable

### VHF/UHF Go-box

I have a [Tytera TYT-8600](rigs.qmd#tytera-tyt-th-8600) radio in a small go-box configuration with an included 12 Ah Bioenno $LiFePO_4$ battery.

## Remote

One technical challenge I enjoy involves remote operations.

### Flex-6400

The [Flex-6400](rigs.qmd#flexradio-6400) can be remotely operated via the SmartConnect link embedded in the radio's software.

I especially enjoy using the [Mac OS](https://roskosch.de/smartsdr-for-mac/) and [iOS](https://roskosch.de/smartsdr-features/) SmartSDR clients.
They work extremely well.

### ICOM IC-705

The same developer of the SmartSDR for Mac and iOS has developed a set of applications for remote access to selected ICOM transceivers called SDR-Control.
The application runs on [MacOS](https://roskosch.de/sdr-control/), [iPad](https://roskosch.de/sdr-control-ios/), and [iPhone](https://roskosch.de/sdr-control-mobile/).

I have successfully used SDR-Control to access my [IC-705](rigs.qmd#icom-ic-705), and have tested it with another operator's IC-7610.

### ICOM IC-7300

The [IC-7300](rigs.qmd#icom-ic-7300) does not have the network circuitry needed to permit "out-of-the-box" control like the [IC-705](rigs.qmd#icom-ic-705) or IC-7610 using SDR-Control. Apparently, there is a USB control option that I have yet to explore.

However, I do use and enjoy remote control of my [IC-7300](rigs.qmd#icom-ic-7300) using the [RemoteTx.net service](https://remotetx.net).
This service allows me to access my IC-7300 from a web browser.

I have experimented with remote control via an early version of the RigPi station server.

