---
title: "Computers"
format: html
editor: source
params:
  software_fn: "w3tm-shack-software"
---

Computers are an integral part of amateur radio.
Here are some descriptions of the computers and software I use in my operations.

## Windows

I have Beelink PC in my home shack that is the main control computer for the Flex-6400 and logging computer for the Flex-6400 and the IC-7300.

I have an Evolve III netbook that I use for portable operations and to retrieve Winlink messages when I am at home using the IC-705 and the W3SWL-10 VHF Winlink node.

## Mac OS

### Mac mini

My W3TM-11 APRS I-Gate runs on a repurposed Mac Mini running Ubuntu 19.04 and the [direwolf](https://github.com/wb2osz/direwolf) software TNC.
It's not fast, but it is extremely stable.
Go Linux!
I connect to it via VNC or local keyboard and mouse.

### Macbook Pro

I bought a Macbook Pro in the summer of 2020 when my Penn State-issued laptop broke.

I use it for personal activities, including amateur radio. It runs the SDR-Control software.

## iOS

I use my iPad to connect to my [Flex-6400](rigs.qmd#flexradio-6400), my [IC-705](rigs.qmd#icom-ic-705), and when I am connected to the NARC clubhouse station's VPN, the club's Flex-6400M and IC-7610. I can also use my iPhone for these purposes, but I prefer the larger iPad screen.

The [SmartSDR](https://roskosch.de/smartsdr-features/) and [SDR-Control](https://roskosch.de/sdr-control-ios/) applications contain PSK31, RTTY, and FT8 clients.

## Android

I have a small Lenovo tablet that I use for APRSDroid and NanoVNA connectivity.

## Raspberry Pi

My [ClearNode Allstar node](#rigs.qmd#clearnode) runs on a dedicated Raspberry Pi.

I have a Raspberry Pi dedicated to the [RemoteTx.net](https://remotetx.net) service connected to my [IC-7300](rigs.qmd#ic-7300).

My HamClock application runs on a dedicated Raspberry Pi 3B+ with a 7" touchscreen.

My [NodeRed server](workbench.qmd#nodered) runs on a Raspberry Pi, but is currently offline.

## Software

In 2024, I started keeping track of the software versions used on the Nittany Amateur Radio Club's mountaintop club station using a Google Sheet.
I update the sheet anytime I upgrade software versions.
Then, I can download the update log and present it in the club's operating manual.
I use a similar workflow here.

```{r}
#| label: retrieve-software-version-file
#| echo: false
#| message: false

csv_path <- file.path("include", "csv")
if (!dir.exists(csv_path)) {
  assertthat::is.writeable(csv_path)
  message("Creating missing file path: ", csv_path)
  dir.create(csv_path)
}

options(gargle_oauth_email = Sys.getenv("GMAIL_ACCT"))
googledrive::drive_auth()

assertthat::is.string(params$software_fn)
googledrive::drive_download(
  params$software_fn,
  path = file.path("include/csv", "w3tm-software-versions.csv"),
  type = "csv",
  overwrite = TRUE
)
```

### Logging

I use Amateur Contact Log, more commonly known as N3FJP's logging software for logging.
The iOS apps I use with my [Flex-6400](rigs.qmd#flexradio-flex-6400) and [IC-705](rigs.qmd#icom-ic-705) have built-in logs that I periodically export and then import into ACLog.
At our club's Field Day, I use N1MM+.

### Digital modes

- WSTJ-X
- JS8Call
- fldigi
- Winlink
  - VARA FM
  - VARA HF
- VarAC
